### ISSUE TITLE
Error when setting slot.(slot 설정시 오류)

### ISSUE THREAD

**Issue by kkh975** [naver/egjs-infinitegrid#305]
아래와 URL에 들어가 보시면, 
GridLayout 안에 slot이 설정되면 아래와 같이 동일한 에러가 발생합니다. 

```
Error in nextTick: "TypeError: Cannot read property 'tagName' of undefined"
```

테스트 확인 URL: 
https://codesandbox.io/s/vue-template-fu408

**Comment by WoodNeck** [comment]
> The question is about setting "slot" inside GridLayout triggers error.

Hello, @kkh975!
I'm afraid that the demo you gave doesn't work.
Looks like the `list` variable is not defined on the component's data.

It seems like the only `slot` used here is "loading", which is correct.
But, as the Infinitegrid is using `slots.default` as children, I'd suggest you to better not use slot other than "loading".

If there's a case that "slot" other than "loading" must be used, please tell us so that we can update our component.

Thanks.

---

안녕하세요.
주신 데모 링크가 slot 이외의 이유로 작동하지 않는 것 같습니다.
확인해보기론 `list` 변수가 data 내에 정의되어 있지 않아서 발생한 문제 같네요.

데모를 확인해보니 사용하고 계신 slot은 "loading" 하나로 보이는데, 올바른 경우입니다.
혹시 그 외를 말씀하시는 거라면, vue-infinitegrid에서 현재 허용하고 있는 slot은 "loading" 하나뿐입니다.
때문에, 그 외의 경우 infinitegrid 내에서 `slots.default`를 기준으로 렌더링하고있기 때문에 렌더링되지 않을 것입니다.

혹시나 "loading" 이외의 slot을 반드시 사용할 일이 있다면, 알려주시면 저희가 반영하여 업데이트할 수 있도록 하겠습니다.

감사합니다.

**Comment by kkh975** [comment]
@WoodNeck 
제가 잠깐 소스 수정하는 사이에 검토가 이루어지신것 같습니다.
현재 다시 업데이트 했습니다.
(언급하신 대로 data내에 list를 추가했습니다.)
```
  data() {
    return {
      list: [{ title: "a" }, { title: "b" }, { title: "c" }],
      olist: []
    };
  },
```
화면상에는 정상 출력되나 
codesandbox에서 제공하는 콘솔박스에는 아래와 같이 출력됩니다.
<img width="649" alt="스크린샷 2019-11-29 오후 3 47 35" src="https://user-images.githubusercontent.com/1680132/69849303-a553af80-12bf-11ea-936d-209dc4f91ef8.png">

로컬에서 잠깐 테스트 했을때 보니깐,
elements 배열안에 slot 태그를 undefined로 추가되어 생기는 문제 같습니다.
(slot을 제거하면 잘 됩니다.)

추가적으로 특정 ajax fetch 이후 데이터를 업데이트 하는 방법이 있을까요?
문서에 적용된 youtube 예제는 내부 onAppend 함수에서 이루어 지는데 외부에서 data를 넣어야 하는 상황입니다.

**Comment by WoodNeck** [comment]
Hello, I've just checked your demo again.

I think that the problem is the duplicated key when rendering `oList`, there're items with the same key, so it makes some elements won't be rendered so that error happens.

---

안녕하세요, 수정하신 데모 확인해봤습니다.
현재 `oList`를 기준으로 렌더링을 하고 계신데, 이를 확인해보시면 key가 동일한 아이템들이 추가되는 것을 확인하실 수 있습니다.
![image](https://user-images.githubusercontent.com/26213435/69851298-b5ba5900-12c4-11ea-8a52-93911d807e92.png)
> "item3" 키가 2개

때문에, 이를 수정하여 getItems() 메소드에서 아이템마다 다른 키를 가져올 수 있도록 수정하시면 정상동작합니다.

```diff
export default {
  data() {
    return {
      list: [{ title: "a" }, { title: "b" }, { title: "c" }],
      olist: [],
+      start: 0
    };
  },
  mounted() {
    // console.log(this.$refs.ig);
    // this.$refs.ig.startLoading();
  },
  methods: {
    onAppend({ groupKey, startLoading, endLoading }) {
      console.log("onAppend");
      // if (this.$refs.ig.isProcessing()) return;
      startLoading();

      const nList = this.getItems(
        this.list,
        parseFloat(groupKey || 0) + 1,
+        this.start
      );
      this.olist.push(...nList);
      endLoading();
    },
    onLayoutComplete({ isLayout, endLoading }) {
      !isLayout && endLoading();
    },
    getItems(items, groupKey, start) {
+      this.start += items.length;

      return items.map((item, i) => {
        const { title } = item;

        return {
          title,
          groupKey,
          key: `item${start + i}`
        };
      });
    }
  }
};
```
